service: teaching
runtime: python311
entrypoint: gunicorn -b :$PORT main:app

env_variables:
  DATABASE_URL: 'postgresql+psycopg2://aiforimpact:Meer2025%22%25@/aiforimpact?host=/cloudsql/aiforimpact:me-central1:aiforimpact'
